name: Cron

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run-cron:
    environment: ${{ github.ref == 'refs/heads/main' && 'main' || 'development' }}
    name: Run Cron
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - run: |
          echo "Running CRON job..."