name: "Update Configuration and Build"

on:
  workflow_dispatch:
  push:

jobs:
  update:
    name: "Update Configuration & Build"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: Meniole/action-deploy-plugin@main
        env:
          appId: ${{ secrets.APP_ID }}
          appPrivateKey: ${{ secrets.APP_PRIVATE_KEY }}
